
app:
  version: 0.1.0-dev
  host: 0.0.0.0
  port: 10011
  debug: true
  file_dir: /tmp
  log_path: logs/
  doc: data/
  token: qiyin
  openai_api_key: EMPTY

###############################
# LLM langchain config
###############################

inference:
  device: cuda

# TODO:These can be modified in api
model:
  history: 0
  temperature: 0.01
  top_k: 5
  top_p: 0.9

###############################
# LLM fastchat config
###############################
fastchat:
  models:
    model_path: lmsys/vicuna-7b-v1.3
    llm_model_name: gpt-3.5-turbo
    embedding_model_name: text-embedding-ada-002
  controller:
    host: 127.0.0.1
    port: 20001
  model_worker:
    host: 127.0.0.1
    port: 20002
    limit_worker_concurrency: 5
    device: cuda
    num_gpus: 1
    max_gpu_memory: 20GiB
  openai_api_server:
    host: 0.0.0.0
    port: 8888

###############################
# Milvus config
###############################
milvus:
  host: 127.0.0.1
  port: 19530
  top_k: 5
  score_threshold: 0.5